version: '3.2'

services:
  postgis:
    image: postgis/postgis:latest
    restart: always
    container_name: postgis
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=pwd0123456789
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
